### ISSUE TITLE
Mana plus fails to start in wayland.

### ISSUE THREAD

**Issue by FoundOne** [flathub/org.manaplus.ManaPlus#8]
It just fails with:
```
Error: Could not initialize SDL: No available video device
```
my setup:
compositor: river-0.1.1_1 (wlroots based) with xwayland
Void Linux x86_64-musl
`echo $DISPLAY` returns `:0` as it should be and all other x11 apps work (both flathub and native).

**Comment by AsciiWolf** [comment]
Thanks for reporting your issue. I did not have any problem on my GNOME Wayland system. I will re-test it.

**Comment by AsciiWolf** [comment]
I can reproduce your issue, however only after disabling the X11 socket. Hmm, this is strange, I am pretty sure it used to work fine on native Wayland. Anyway, I will remove the Wayland socket for now.

**Comment by AsciiWolf** [comment]
It works fine on XWayland on my machine and hopefully will work on your system too after the Wayland socket is removed.
